// Code generated by go-swagger; DO NOT EDIT.

package search_parameter

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewTitleSearchParams creates a new TitleSearchParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewTitleSearchParams() *TitleSearchParams {
	return &TitleSearchParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewTitleSearchParamsWithTimeout creates a new TitleSearchParams object
// with the ability to set a timeout on a request.
func NewTitleSearchParamsWithTimeout(timeout time.Duration) *TitleSearchParams {
	return &TitleSearchParams{
		timeout: timeout,
	}
}

// NewTitleSearchParamsWithContext creates a new TitleSearchParams object
// with the ability to set a context for a request.
func NewTitleSearchParamsWithContext(ctx context.Context) *TitleSearchParams {
	return &TitleSearchParams{
		Context: ctx,
	}
}

// NewTitleSearchParamsWithHTTPClient creates a new TitleSearchParams object
// with the ability to set a custom HTTPClient for a request.
func NewTitleSearchParamsWithHTTPClient(client *http.Client) *TitleSearchParams {
	return &TitleSearchParams{
		HTTPClient: client,
	}
}

/* TitleSearchParams contains all the parameters to send to the API endpoint
   for the title search operation.

   Typically these are written to a http.Request.
*/
type TitleSearchParams struct {

	/* Callback.

	   JSONP callback name
	*/
	Callback *string

	/* Page.

	   Page number to return
	*/
	Page *int64

	/* R.

	   The response type to return
	*/
	R *string

	/* S.

	   Title of movie or series
	*/
	S string

	/* Type.

	   Return movie or series
	*/
	Type *string

	/* Y.

	   Year of release
	*/
	Y *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the title search params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TitleSearchParams) WithDefaults() *TitleSearchParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the title search params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TitleSearchParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the title search params
func (o *TitleSearchParams) WithTimeout(timeout time.Duration) *TitleSearchParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the title search params
func (o *TitleSearchParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the title search params
func (o *TitleSearchParams) WithContext(ctx context.Context) *TitleSearchParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the title search params
func (o *TitleSearchParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the title search params
func (o *TitleSearchParams) WithHTTPClient(client *http.Client) *TitleSearchParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the title search params
func (o *TitleSearchParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCallback adds the callback to the title search params
func (o *TitleSearchParams) WithCallback(callback *string) *TitleSearchParams {
	o.SetCallback(callback)
	return o
}

// SetCallback adds the callback to the title search params
func (o *TitleSearchParams) SetCallback(callback *string) {
	o.Callback = callback
}

// WithPage adds the page to the title search params
func (o *TitleSearchParams) WithPage(page *int64) *TitleSearchParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the title search params
func (o *TitleSearchParams) SetPage(page *int64) {
	o.Page = page
}

// WithR adds the r to the title search params
func (o *TitleSearchParams) WithR(r *string) *TitleSearchParams {
	o.SetR(r)
	return o
}

// SetR adds the r to the title search params
func (o *TitleSearchParams) SetR(r *string) {
	o.R = r
}

// WithS adds the s to the title search params
func (o *TitleSearchParams) WithS(s string) *TitleSearchParams {
	o.SetS(s)
	return o
}

// SetS adds the s to the title search params
func (o *TitleSearchParams) SetS(s string) {
	o.S = s
}

// WithType adds the typeVar to the title search params
func (o *TitleSearchParams) WithType(typeVar *string) *TitleSearchParams {
	o.SetType(typeVar)
	return o
}

// SetType adds the type to the title search params
func (o *TitleSearchParams) SetType(typeVar *string) {
	o.Type = typeVar
}

// WithY adds the y to the title search params
func (o *TitleSearchParams) WithY(y *int64) *TitleSearchParams {
	o.SetY(y)
	return o
}

// SetY adds the y to the title search params
func (o *TitleSearchParams) SetY(y *int64) {
	o.Y = y
}

// WriteToRequest writes these params to a swagger request
func (o *TitleSearchParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Callback != nil {

		// query param callback
		var qrCallback string

		if o.Callback != nil {
			qrCallback = *o.Callback
		}
		qCallback := qrCallback
		if qCallback != "" {

			if err := r.SetQueryParam("callback", qCallback); err != nil {
				return err
			}
		}
	}

	if o.Page != nil {

		// query param page
		var qrPage int64

		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt64(qrPage)
		if qPage != "" {

			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}
	}

	if o.R != nil {

		// query param r
		var qrR string

		if o.R != nil {
			qrR = *o.R
		}
		qR := qrR
		if qR != "" {

			if err := r.SetQueryParam("r", qR); err != nil {
				return err
			}
		}
	}

	// query param s
	qrS := o.S
	qS := qrS
	if qS != "" {

		if err := r.SetQueryParam("s", qS); err != nil {
			return err
		}
	}

	if o.Type != nil {

		// query param type
		var qrType string

		if o.Type != nil {
			qrType = *o.Type
		}
		qType := qrType
		if qType != "" {

			if err := r.SetQueryParam("type", qType); err != nil {
				return err
			}
		}
	}

	if o.Y != nil {

		// query param y
		var qrY int64

		if o.Y != nil {
			qrY = *o.Y
		}
		qY := swag.FormatInt64(qrY)
		if qY != "" {

			if err := r.SetQueryParam("y", qY); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
